"""recreate initial

Revision ID: 126262bf95fa
Revises: 
Create Date: 2025-11-06 11:18:46.135106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126262bf95fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
     # When converting from string to timestamp PostgreSQL may require
     # an explicit USING clause to cast the existing data. Provide a
     # postgresql_using expression to avoid the automatic-cast error.
     batch_op.alter_column('completed_at',
         existing_type=sa.VARCHAR(),
         type_=sa.DateTime(),
         existing_nullable=True,
         postgresql_using="completed_at::timestamp without time zone")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
     # Reverse the cast when downgrading.
     batch_op.alter_column('completed_at',
         existing_type=sa.DateTime(),
         type_=sa.VARCHAR(),
         existing_nullable=True,
         postgresql_using="completed_at::varchar")

    # ### end Alembic commands ###
