"""empty message

Revision ID: 7ddc422cf4eb
Revises: a4b31f47f3ee
Create Date: 2025-11-04 23:25:32.963429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddc422cf4eb'
down_revision = 'a4b31f47f3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('task_goal_id_fkey', type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_goal_id_fkey', 'goal', ['goal_id'], ['id'])
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='goal_pkey')
    )
    # ### end Alembic commands ###
